services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - mynet

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
    ports:
      - "5432:5432"
    networks:
      - mynet
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d


volumes:
  db_data:

networks:
  mynet:
